replicaCount: 2

image:
  repository: 034255117140.dkr.ecr.eu-central-1.amazonaws.com/dev-django-app
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  dbHost: "dev-django-db-rds.ctskymysi6zv.eu-central-1.rds.amazonaws.com"
  dbName: "django_db"
  dbUser: "django_user"
  dbPort: "5432"
  djangoDebug: "False"

secrets:
  dbPassword: "SuperSecurePassword123"
  secretKey: "django-insecure-random-secret-key-value"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
