replicaCount: 1

image:
  repository: django-app
  tag: "latest"
  pullPolicy: IfNotPresent

config:
  dbName: "django_db"
  dbUser: "postgres"
  dbPort: "5432"
  dbHost: "rds-postgres-address-from-terraform"
  djangoDebug: "True"
  allowedHosts: "*"

secret:
  dbPassword: "SuperSecretPassword123"
  secretKey: "django-insecure-yoursupersecretproductionkey"
