apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DJANGO_DEBUG: {{ .Values.config.djangoDebug | quote }}
  ALLOWED_HOSTS: {{ .Values.config.allowedHosts | quote }}