containers:
        - name: django-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "django-app.fullname" . }}-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "django-app.fullname" . }}-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "django-app.fullname" . }}-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "django-app.fullname" . }}-config
                  key: DB_PORT
            - name: DJANGO_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "django-app.fullname" . }}-config
                  key: DJANGO_DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "django-app.fullname" . }}-config
                  key: ALLOWED_HOSTS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-app.fullname" . }}-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "django-app.fullname" . }}-secret
                  key: SECRET_KEY