apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: django-app-config

          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-app-secret
                  key: SECRET_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-app-secret
                  key: DB_PASSWORD

          ports:
            - containerPort: 8000

          resources:
{{ toYaml .Values.resources | indent 12 }}