apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-app.fullname" . }}-secret
type: Opaque
data:
  SECRET_KEY: {{ .Values.django.secretKey | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}