apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc }}
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc }}